# Generated by Django 3.2.5 on 2021-08-31 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_T',
            fields=[
                ('assessmentID', models.AutoField(primary_key=True, serialize=False)),
                ('assessmentName', models.CharField(max_length=30)),
                ('questionNum', models.IntegerField()),
                ('totalMarks', models.FloatField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_T',
            fields=[
                ('courseID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50, null=True)),
                ('numOfCredits', models.DecimalField(decimal_places=1, max_digits=2)),
                ('courseType', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Department_T',
            fields=[
                ('departmentNum', models.AutoField(primary_key=True, serialize=False)),
                ('departmentID', models.CharField(max_length=5)),
                ('departmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_T',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('accountAddress', models.CharField(max_length=30, null=True)),
                ('accountType', models.CharField(max_length=1, null=True)),
                ('instructorID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('startDate', models.DateField(null=True)),
                ('rank', models.CharField(max_length=50, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.department_t')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program_T',
            fields=[
                ('programID', models.AutoField(primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=70)),
                ('department', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='spmapp.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='University_T',
            fields=[
                ('universityID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('universityName', models.CharField(max_length=50)),
                ('universityAddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VC_T',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('accountAddress', models.CharField(max_length=30, null=True)),
                ('accountType', models.CharField(max_length=1, null=True)),
                ('vcID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('startDate', models.CharField(default='N/A', max_length=15)),
                ('endDate', models.CharField(default='N/A', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student_T',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('accountAddress', models.CharField(max_length=30, null=True)),
                ('accountType', models.CharField(max_length=1, null=True)),
                ('studentID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('enrollmentDate', models.DateField(null=True)),
                ('graduateDate', models.DateField(null=True)),
                ('program', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='spmapp.program_t')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section_T',
            fields=[
                ('sectionID', models.AutoField(primary_key=True, serialize=False)),
                ('sectionNum', models.IntegerField()),
                ('sec_semester', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.course_t')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.instructor_t')),
            ],
        ),
        migrations.CreateModel(
            name='School_T',
            fields=[
                ('schoolNum', models.AutoField(primary_key=True, serialize=False)),
                ('schoolID', models.CharField(max_length=5)),
                ('schoolName', models.CharField(max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.university_t')),
            ],
        ),
        migrations.CreateModel(
            name='Registration_T',
            fields=[
                ('regID', models.AutoField(primary_key=True, serialize=False)),
                ('reg_semester', models.CharField(max_length=15)),
                ('year', models.IntegerField(default=2020, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.section_t')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.student_t')),
            ],
        ),
        migrations.CreateModel(
            name='PrereqCourse_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='spmapp.course_t')),
                ('preReqCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreRequisite', to='spmapp.course_t')),
            ],
        ),
        migrations.CreateModel(
            name='PLO_T',
            fields=[
                ('ploID', models.AutoField(primary_key=True, serialize=False)),
                ('ploNum', models.CharField(max_length=5)),
                ('plodetails', models.CharField(max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.program_t')),
            ],
        ),
        migrations.CreateModel(
            name='Head_T',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('accountAddress', models.CharField(max_length=30, null=True)),
                ('accountType', models.CharField(max_length=1, null=True)),
                ('headID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('startDate', models.CharField(default='N/A', max_length=15)),
                ('endDate', models.CharField(default='N/A', max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.department_t')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation_T',
            fields=[
                ('evaluationID', models.AutoField(primary_key=True, serialize=False)),
                ('obtainedMarks', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.assessment_t')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.instructor_t')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.registration_t')),
            ],
        ),
        migrations.AddField(
            model_name='department_t',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.school_t'),
        ),
        migrations.CreateModel(
            name='Dean_T',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('accountAddress', models.CharField(max_length=30, null=True)),
                ('accountType', models.CharField(max_length=1, null=True)),
                ('deanID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('startDate', models.CharField(default='N/A', max_length=15)),
                ('endDate', models.CharField(default='N/A', max_length=15)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.school_t')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course_t',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.program_t'),
        ),
        migrations.CreateModel(
            name='CO_T',
            fields=[
                ('coID', models.AutoField(primary_key=True, serialize=False)),
                ('coNum', models.CharField(max_length=4)),
                ('thresold', models.FloatField(default=40)),
                ('course', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='spmapp.course_t')),
                ('plo', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='spmapp.plo_t')),
            ],
        ),
        migrations.CreateModel(
            name='CO_Course_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_semester', models.CharField(max_length=15)),
                ('co_year', models.IntegerField(default=2020, null=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.co_t')),
                ('course', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='spmapp.course_t')),
            ],
        ),
        migrations.AddField(
            model_name='assessment_t',
            name='coID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.co_t'),
        ),
        migrations.AddField(
            model_name='assessment_t',
            name='instructorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.instructor_t'),
        ),
        migrations.AddField(
            model_name='assessment_t',
            name='sectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.section_t'),
        ),
    ]
